// as we have seen in the previous examples, you can use several aspects of the data at the same time:

// use the fluctuation measure to set the sensitivity:
// use the standard deviation to set the amplitude
// use the mean to set the frequency of the sinetones

// you could also use triggers to start different sounds, while still using the continuous data stream to change parameters in the sound
